apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: auth
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: AUTH_IMAGE
        env:
          - name: AuthorizationDatabaseSettings__ConnectionString
            valueFrom:
              secretKeyRef:
                name: database-string
                key: connection_string
          - name: AppSettings__Secret
            valueFrom:
              secretKeyRef:
                name: token-string
                key: token_string
        ports:
          - name: http
            containerPort: 80
            hostPort: 80 ### this will bind to port 80 on the actual node
        livenessProbe:      # Used by deployment controller
          httpGet:
            path: /api/Version
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 200
        readinessProbe:     # Used by Ingress/GCLB
          httpGet:
            path: /api/Version
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 200
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
